neo4j:
    profiling:
        enabled: true
    connections:
        default:
            scheme: http
            host: 127.0.0.1
            port: 7474
            username: neo4j
            password: 1548
